### ISSUE TITLE
Out-of-bounds memory access in sha test 

### ISSUE THREAD

**Issue by niosHD** [pulp-platform/pulpino#101]
The [data array](https://github.com/pulp-platform/pulpino/blob/master/sw/apps/bench/sha/sha_test.c#L14) in the sha test (i.e., `sw/apps/bench/sha`) has a size of 256 bytes. However, [during hash computation](https://github.com/pulp-platform/pulpino/blob/master/sw/apps/bench/sha/sha_test.c#L26) up to 16 additional bytes get processed because an offset is added to the base pointer in the loop without adopting the corresponding length.

Regards,
Mario

**Comment by be4web** [comment]
Thanks for the pointer. Would you consider to submit a PR to fix this issue? Thanks

**Comment by niosHD** [comment]
Sure, I can look into it. However, I doubt that I have time to properly fix the issue within the next weeks.

**Comment by FrancescoConti** [comment]
Fixed as of https://github.com/pulp-platform/pulpino/tree/6370c5f
