### ISSUE TITLE
Cannot find tcl_files/config/vsim_ips.tcl

### ISSUE THREAD

**Issue by zhehescarlett** [pulp-platform/pulpino#103]
I am trying to run the helloworld application you provided by running
make helloworld.vsimc
But get a glitch like
Cannot find tcl_files/config/vsim_ips.tcl

**Comment by FrancescoConti** [comment]
Have you run update-ips.py / generate-scripts.py first? The "missing" file is generated by those scripts.

Il giorno 14 ago 2017, alle ore 10:12, zhehescarlett <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I am trying to run the helloworld application you provided by running
make helloworld.vsimc
But get a glitch like
Cannot find tcl_files/config/vsim_ips.tcl

-
