### ISSUE TITLE
Running new programs on zedboard implementation

### ISSUE THREAD

**Issue by ninode** [pulp-platform/pulpino#105]
Hello, 

I would like to know how I can 1) toggle zedboard LEDs with this implementation, and 2) run binaries on the rocket core ? Could you please provide some pointers ?

Thank you

**Comment by be4web** [comment]
I am pretty sure that there is an LED example already included. Look at the [FPGA readme](https://github.com/pulp-platform/pulpino/tree/master/fpga). We do not support Rocket, head over the [guys from Berkeley](https://github.com/freechipsproject/rocket-chip) for that.
