### ISSUE TITLE
Peripherals and memory

### ISSUE THREAD

**Issue by fathomtreelimited** [pulp-platform/pulpino#106]
Hi!

The description and diagrams suggest you have i2s on the APB bus.  Do you have any specifications for this audio interface?

For memory support please take a look at implementing octal SPI (250Mhz) so designers can use the flash and ram solutions from Macronix.  At just 13pins required this seems like a good alternative to DDR memories and phys.

OctaFlash (to 2Gb)
OctaRAM (to 128Mbit)
OctaMCP (512Mbit flash, 128Mbit ram)

250Mhz Octal SPI gives speeds to 400MB/sec.

http://www.macronix.com/en-us/about/news/Pages/Macronix-Unveils-New-Generation-Low-Pin-Count-OctaBus-Memory-Subsystem-Solution-for-IoT-and-Automotive-Electronics-Markets.aspx 

Best regards,
David.

**Comment by be4web** [comment]
Thanks for the pointer - we are aware of Cypress's HyperRam which is indeed interesting for us. Regarding I2S, we do have an I2S peripheral, but I do not think that we have open-sourced it yet. So I think the data on the website might be a little unaligned with reality. Sorry for that.

**Comment by fathomtreelimited** [comment]
Ok, thanks.  HyperBus and the Macronix parts are great little parts. Do you have any documentation you can share about the i2s peripheral?
