### ISSUE TITLE
do you have the i2s implemented?

### ISSUE THREAD

**Issue by yuz835** [pulp-platform/pulpino#108]
i just found the README from this proj, and the i2s peripherals is included.
but I didnt find

For communication with the outside world, PULPino contains a broad set of peripherals, including **I2S**, I2C, SPI and UART. The platform internal devices can be accessed from outside via JTAG and SPI which allows pre-loading RAMs with executable code. In standalone mode, the platform boots from an internal boot ROM and loads its program from an external SPI flash.

**Comment by be4web** [comment]
We do have an I2S, but apparently not open-sourced (yet).

**Comment by yuz835** [comment]
any schedule to release it?
