### ISSUE TITLE
extensions / simd

### ISSUE THREAD

**Issue by fathomtreelimited** [pulp-platform/pulpino#109]
Hi!

Do you have a guide or mini tutorial about extending the core instructions? I have a particular fixed point math that I would like to implement.

Precision Integer MAC for OTT "over the top" audio processing

64-bit audio word made up of
- 8 bit overhead/guard
- 32-bit sample
- 24-bit noise

Multiply the above sample by set of 32-bit coefficient(s).

Store product in a 96-bit accumulator
- 8 bits headroom
- 32 bits sample
- 32 bits coefficient
- 24 bits noise

Is this kind of ALU extension or instruction module possible?

Thanks!

**Comment by FrancescoConti** [comment]
It's surely possible, but unfortunately at the moment we do not provide any guide for this. You can have a look here [https://arxiv.org/pdf/1608.08376.pdf](https://arxiv.org/pdf/1608.08376.pdf) if you want to have a more high-level presentation of how the core was modified as a past; that can provide some guidance.
