### ISSUE TITLE
PPA Results Comparison

### ISSUE THREAD

**Issue by riscveval** [pulp-platform/pulpino#117]
Hi i am evaluating the various RISCV Cores. I want to compare the PPA for various cores. For that i am getting the following results for Pulpino....

Core | ISA | Bit | Pipeline | LUTs | LUT RAMs | LUT FFs | BRAM | Power µW/MHz | Dhrystone DMIPS/   MHz | Coremark /MHz | Target FPGA
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Pulpino | RV32IMFC | 32 | 4 | 12449 | 41 | 11093 | 16 | 0.018 | 1.21 | 3.19 | Zed Board

 These results are correct or not? Otherwise can you share these information to me.

How to change the cache memories? Cache memories are configurable for pulpino?

**Comment by FrancescoConti** [comment]
Hi, you can find the relevant information [here](http://www.pulp-platform.org/documentation/). The data you have seems to be referring to the RI5CY core.
We do not utilization results in terms of LUTs, sorry.
