### ISSUE TITLE
dump VCD file -error

### ISSUE THREAD

**Issue by samisalamin** [pulp-platform/pulpino#121]
Hi,
I installed pulpino, and I'm trying to dump the VCD file.
I used 
make helloworld.power
make helloworld.powerc
unfortunately, I got an error  of missed file
# couldn't read file "tcl_files/run_power.tcl": no such file or directory

# source tcl_files/run_power.tcl
# couldn't read file "tcl_files/run_power.tcl": no such file or directory
#  run -a
# No Design Loaded!
#  exit

I can not find this file anywhere, please anyone can advise??
thanx

**Comment by be4web** [comment]
You do power simulations on the post-layout nestlists (sometimes also on the post-synthesis netlists). We do not provide the flow to generate those, hence we also do not provide power simulation scripts. You will need to develop/extend your own flow, highly depending on the tools you use.
