### ISSUE TITLE
which debugger can use this platform

### ISSUE THREAD

**Issue by Pengnian** [pulp-platform/pulpino#128]
Hi expert,
we have generated bitstream file for our Board(Virtex UltraScala+ VCU118) but don't know how to upload
application execute in pulpino core  so I want to know which debugger we can use it to upload,debugging our application. please give me some hints~  Thanks!!!

**Comment by be4web** [comment]
We unfortunately cannot give support for other FPGA boards. 

I can just tell you how I did it:

1. Use the JTAG debug already available on PULPino
2. Use an FTDI JTAG capable adapter (like the Olimex ARM Debugger)
3. Extend the debug_bridge to use the FTDI

It is not a terrible difficult job to do but will require some reverse engineering (you can see JTAG access patterns in the TB) and deeper understanding.
