### ISSUE TITLE
128 bits prefectcher

### ISSUE THREAD

**Issue by Mexami** [pulp-platform/pulpino#129]
Hi,

I wish to use the 128-bit size of the ri5cy prefetcher.
Is there some synthesis options for set the prefetcher size and propagate the involved modifications in the core.
Or i have to modify the buses and memory width by myself?

Thank you

**Comment by davideschiavone** [comment]
Hello,

the 128b prefetcher  is  used in our multicore cluster and it is used to fetch one cache line.
Pulpino does not support it so you have to modify the system accordingly.

best
Davide
