### ISSUE TITLE
how to transplantation pulpino to other  board (UltraScala+ VCU118)

### ISSUE THREAD

**Issue by Pengnian** [pulp-platform/pulpino#132]
Hi experts,

At first,thanks for your share ! 

I want to transplantation pulpion to my board, but redeme file no relative steps about to other board . I'm running simulation and test in zedboard  is  all okay, so please give me steps about transplantation pulpino.

Thanks very much!

**Comment by FrancescoConti** [comment]
Assuming what you want is to port PULPino to another board: since we provide RTL + scripts for Vivado, it shouldn’t be too difficult, but to support that we would have had to do it ourselves, which we have not.
