### ISSUE TITLE
FPGA awk: symbol lookup error: awk: undefined symbol

### ISSUE THREAD

**Issue by javiermacotela** [pulp-platform/pulpino#135]
Hello I am using Ubuntu 16.04.3 LTS,
Vivado 2015.1 and the corresponding SDK.
When trying to make all in the fpga folder I get the following error:

make[1]: Entering directory '/home/jvmacotela/Documents/embedded-electronics/ic-project/pulpino/fpga/sw'
cd linux-xlnx && make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi- UIMAGE_LOADADDR=0x8000 uImage PATH=/home/jvmacotela/Documents/embedded-electronics/ic-project/pulpino/fpga/sw/u-boot-xlnx/tools/:/opt/Xilinx/Vivado/2015.1/bin:/opt/Xilinx/SDK/2015.1/bin:/opt/Xilinx/SDK/2015.1/gnu/microblaze/lin/bin:/opt/Xilinx/SDK/2015.1/gnu/arm/lin/bin:/opt/Xilinx/SDK/2015.1/gnu/microblaze/linux_toolchain/lin64_be/bin:/opt/Xilinx/SDK/2015.1/gnu/microblaze/linux_toolchain/lin64_le/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jvmacotela/Documents/embedded-electronics/ic-project/ri5cy_gnu_toolchain/install/bin:/home/jvmacotela/altera/15.0/modelsim_ase/linuxaloem:/opt/Xilinx/Vivado/2015.1/bin:/opt/Xilinx/SDK/2015.1/bin -j4
make[2]: Entering directory '/home/jvmacotela/Documents/embedded-electronics/ic-project/pulpino/fpga/sw/linux-xlnx'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Generating include/generated/mach-types.h
awk: symbol lookup error: awk: undefined symbol: mpfr_z_sub
arch/arm/tools/Makefile:8: recipe for target 'include/generated/mach-types.h' failed
make[3]: *** [include/generated/mach-types.h] Error 1
arch/arm/Makefile:295: recipe for target 'archprepare' failed
make[2]: *** [archprepare] Error 2
make[2]: Leaving directory '/home/jvmacotela/Documents/embedded-electronics/ic-project/pulpino/fpga/sw/linux-xlnx'
Makefile:23: recipe for target 'linux-xlnx/arch/arm/boot/uImage' failed
make[1]: *** [linux-xlnx/arch/arm/boot/uImage] Error 2
make[1]: Leaving directory '/home/jvmacotela/Documents/embedded-electronics/ic-project/pulpino/fpga/sw'
Makefile:51: recipe for target 'sw' failed
make: *** [sw] Error 2

I've been trying to find a solution for this in the Xilinxs forums but I have nothing so far, did you have this problem as well? If so, how did you fix it?

Thanks for your help,

Javier

**Comment by be4web** [comment]
It seem that you are not the only one having that problem [1,2]. It's more of a problem related to Xilinx though.

[1] https://forums.xilinx.com/t5/Installation-and-Licensing/XSCT-symbol-lookup-error-awk-undefined-symbol-mpfr-z-sub/m-p/743252/highlight/true#M17345
[2] https://forums.xilinx.com/t5/Installation-and-Licensing/Vivado-2016-4-on-Ubuntu-16-04-LTS-quot-awk-symbol-lookup-error/m-p/756779#M17778
