### ISSUE TITLE
AXI and APB Interfaces

### ISSUE THREAD

**Issue by amohamme** [pulp-platform/pulpino#137]
We have a module that has an AXI and APB interface. Is it possible to connect this module to PULPino via its AXI interconnect or APB bus ?

We need to have something similar to the figure below:

![pulpino_axi_if](https://user-images.githubusercontent.com/33259337/33524499-e779ed28-d826-11e7-8e21-dd22e241e103.jpg)

**Comment by be4web** [comment]
Yes its possible.

**Comment by amohamme** [comment]
Thanks for your reply.
Is there is examples for such cases ? What changes are required (HW/SW) ?

**Comment by f2013619** [comment]
@amohamme I am also trying to connect an external module to the axi bus. Can you tell me how you did it? Specifically how you updated the files. I have tried doing it but the module is working correctly but its not taking the inputs from the core.
It would be a great help. Thanks in advance.
