### ISSUE TITLE
malloc function

### ISSUE THREAD

**Issue by Erik-Chen** [pulp-platform/pulpino#14]
Hi everyone,
   I saw there is a path point to "malloc_lib" at sw/apps/CMakeLists.txt ,but there isn't. Are there any opportunities to use the malloc funciton in the future ? Thank you!

**Comment by gautschimi** [comment]
Hello Eric-chen

Before we had support for an operating system freeRTOS we used a separate lib for dynamic memory management. now we use the support given by freeRTOS, If you check the sources of freeRTOS in sw/apps/freertos/Source/portable/MemMang/ you will find a couple of functions which I believe do exactly the job you are looking for.

best,
Michael
