### ISSUE TITLE
Debugging with GDB problem

### ISSUE THREAD

**Issue by Bassma99** [pulp-platform/pulpino#140]
I have an issue regarding debugging simulations on Questa/Modelsim with GDB. The ri5cy toolchain doesn't provide gdb version compatible withe debug_bridge provided in the pulp-platform repository. 
1) The version installed from the riscv-gnu-toolchain is gdb 8.0. with an updated remote protocol and the debug_bridge doesn't support it (responds incorrectly to vMustReplyEmpty causing gdb to timeout)
2) I checked the issues on the debug_bridge the commit mentioned that works  from the riscv-gnu-toolchain for gdb is no longer available on the repository. this problem was mentioned and referenced here https://github.com/pulp-platform/debug_bridge/issues/1
The question here: 
1) What can i do to solve this issue? is there an available commit i can use from the riscv-gnu-toolchain? or can you link to the one you are using?
2) Is there any modifications that can be done to the remote protocol files in order to quick fix the problem if it is just a minor difference that is causing the problem?

**Comment by FrancescoConti** [comment]
I don't know the answers to 1,3,4. But you should be able to get the correct GDB from here https://github.com/riscv/riscv-binutils-gdb/tree/2a3cd80 (see
https://github.com/pulp-platform/debug_bridge/issues/9 )
