### ISSUE TITLE
Can not see any simulation dumps for PULPino

### ISSUE THREAD

**Issue by thotaraghava** [pulp-platform/pulpino#147]
HI everybody,

   I could not find any simulation dump for pulpino RTL in the repository.
   Please help me in getting this to understand inside.

Thanks,
Raghav

**Comment by FrancescoConti** [comment]
If by "simulation dump" you mean a VCD dump, then it's not there. I don't find any good reason to provide one to be honest; you can run your own simulation as detailed [here](https://github.com/pulp-platform/pulpino/blob/master/README.md#running-simulations).

**Comment by thotaraghava** [comment]
Thanks for your clarification.
