### ISSUE TITLE
Regarding PULPino RTL files

### ISSUE THREAD

**Issue by thotaraghava** [pulp-platform/pulpino#149]
HI all,

    I do not have internet access for my VWP,  hence I need to download to Windows and then transfer.
    With regards to RTL files, all files are here in this web browser or else we need to update in Linux environment to get IPs.

   Please help in this regard.
Thanks,

**Comment by be4web** [comment]
I am really sorry but I have no idea what you are actually asking for... You can always checkout the repo, update the ips and transfer the whole sourcecode.

**Comment by thotaraghava** [comment]
How can I update repo in Windows machine after cloning through GitHub Desktop.

any idea.

**Comment by be4web** [comment]
We do not support windows. You might be able to just run `./update-ips.py` without modifications.

**Comment by thotaraghava** [comment]
Does this command generates any more RTL files for IPs.

**Comment by be4web** [comment]
Yes, this command checks out all necessary IPs from github.

**Comment by thotaraghava** [comment]
ohh ok. Thanks
