### ISSUE TITLE
Issue when trying to run a simulation in ModelSim 

### ISSUE THREAD

**Issue by sourav1394** [pulp-platform/pulpino#153]
Hello all,

I get the following error when I run `make helloworld.vsim`:
`riscv32-unknown-elf-gcc: error: unrecognized command line option '-mhard-float'; did you mean '--warn-format'?`

How do I fix this issue?

Thanks

**Comment by FrancescoConti** [comment]
You should install the correct version of the toolchain as specified in the README here: https://github.com/pulp-platform/ri5cy_gnu_toolchain
