### ISSUE TITLE
Firmware for Pulpino

### ISSUE THREAD

**Issue by thotaraghava** [pulp-platform/pulpino#159]
Hi @FrancescoConti ,

   Can you point me the firmware link to download for PULPINO and the procedure to do this.
   Though simple question it may be, it will help us.

Thanks

**Comment by FrancescoConti** [comment]
Do you mean the firmware for the FPGA port? We don't distribute it in binary form, but you can find all the instructions to build it here https://github.com/pulp-platform/pulpino/tree/master/fpga

**Comment by thotaraghava** [comment]
No, I am not working on FPGA.
I have integrated PULPino in my system in the place of CM3.
Firmware, I mean, instructions to run the processor.
