### ISSUE TITLE
Procedure to Add a New Board

### ISSUE THREAD

**Issue by merchantf** [pulp-platform/pulpino#161]
Hi,

I do not have zedboard or zybo. I have a board from xilinx with Zynq SoC.

Adding the new board does not seem to be trivial. There are several errors. I have one posted in another thread under "Issues". 

I had to edit u-boot.config file to build the OS for the SoC. Even after that it does not work. 

Thanks & Regards,

Farhad

**Comment by FrancescoConti** [comment]
Hi @merchantf , yes - changing the board is not a trivial procedure. Especially for what concerns building the OS, which is not related at all to PULPino. I refer you to Xilinx support and the Xilinx wiki here http://www.wiki.xilinx.com for help. Good luck!
