### ISSUE TITLE
stand alone PULPino simulation

### ISSUE THREAD

**Issue by thotaraghava** [pulp-platform/pulpino#162]
Hi @FrancescoConti ,

     Now, I need to do stand alone PULPino simulations.
     And I do not have internet connection to my Linux machine.
     At present my work space is having PULPino RTL only.
     With patience, can you define steps to do for the setup, so that I can follow.

Thanks a lot,
Raghav

**Comment by FrancescoConti** [comment]
Hi, my answers to your question in issue #156 already contains all the details you need - unfortunately your case is very peculiar (no Internet access) and at the moment we do not provide static packages with all the necessary files in a tarball. Therefore you will have to do your homework following those notes.

Good luck!
