### ISSUE TITLE
SPI slave to process received data

### ISSUE THREAD

**Issue by WaleedOsama** [pulp-platform/pulpino#165]
i want to know the best choice i have to make SPI slave PULPino node aware that data is completely received to begin processing it , and here is what i did.
i simulated on modelsim two PULPinos connected like this 
![dum11](https://user-images.githubusercontent.com/31411635/36013326-39a0a36a-0d6c-11e8-8ce6-7ad80dee9b87.png)

so what happens in the previous figure is that master can write and read data from slave PULPino memory , and in order for slave to know that master finished sending over SPI it waits for character over UART , then it can start processing the data , but this requires that slave to know the size of this data , and address too . this is the most naive way to achieve the goal of slave processing received data.

but this is not what i want , i want SPI slave to not depend on another peripheral to know that master finished , like this 
![dum22](https://user-images.githubusercontent.com/31411635/36013449-fb1b2aba-0d6c-11e8-9ae1-979868c1b63d.png)

so i think optimal way would be if there is some interrupt at slave to tell it that transaction finished and at some known addresses i find the address and size of received block of data . 

but i do not think this interrupt exists here , what i am thinking as closest to that is that i will define these addresses in memory and use SPI master to write in these known places in memory of slave side that:

- it is done
- address it wrote to
- size of block it wrote

and make the slave side by polling wait for done place to be set and go to see the address and size of block of data .
but this takes me to another issue , i do not know how memory management works here , but will it over write this places ?

so my questions are :

1.  is there a better way than what i suggested (better than slave polling on place)?
2.  is there some interrupt that can do what i want at slave SPI side ?
3.  will these places be over written ? , i will use a pointer and write in  memory directly 

thank you

**Comment by FrancescoConti** [comment]
As both PULPino's will be running bare-metal code, there is no memory management essentially :) if you write your code carefully (you statically allocate the variables in the data memory, and you don't introduce races in your code), you shouldn't have problems.

As for a better solution, I think you can set an interrupt on GPIO - however I am not 100% sure whether this is doable in PULPino.

**Comment by WaleedOsama** [comment]
@FrancescoConti  yes it is doable , i just imlpemented it , thanks for your feedback , i think this is the best solution.

**Comment by ravi02011993** [comment]
@WaleedOsama 
Can you tell me what are the changes required in tb to run the simulation in Modelsim for  gpio_demo example?
