### ISSUE TITLE
error ninja vcompile

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulpino#168]
Hey,
I am trying to build the "ninja vcompile" :

![screenshot from 2018-02-13 09-45-00](https://user-images.githubusercontent.com/36438648/36140795-dadedfce-10a2-11e8-89ad-e3f3b9861083.png)

Any suggestions?

**Comment by zarubaf** [comment]
It seems that you don't have ModelSim installed (or in your path): `vlib` command not found.

**Comment by lfernand4** [comment]
What can i do in order to use verilator ?

**Comment by lfernand4** [comment]
In the README from Jun 2017 we can found :
![image](https://user-images.githubusercontent.com/36438648/36142846-862c3038-10a9-11e8-8027-ecda8d33921d.png)

**Comment by zarubaf** [comment]
We currently do not support Verilator with PULPino. You are more then welcome though to add support for it and make a PR ;-)
