### ISSUE TITLE
problem with vcompile

### ISSUE THREAD

**Issue by LilachDery** [pulp-platform/pulpino#174]
hi,

I am trying to make "make vcomiple" as said.
but i got this error: 
make: *** No rule to make target 'vcompile'. Stop.

I try to search after the answer on the internet but i dont find the answer

**Comment by LilachDery** [comment]
I did a build folder, in sw, with cmake_configure file

**Comment by who93** [comment]
is ModelSim in your path? have you first executed the cmake script?

**Comment by FrancescoConti** [comment]
The README.md contains detailed instructions on how to build the simulation platform.
