### ISSUE TITLE
testGPIO.c is not working

### ISSUE THREAD

**Issue by ravi02011993** [pulp-platform/pulpino#175]
![image](https://user-images.githubusercontent.com/28788219/36543083-028f90c6-17e3-11e8-92eb-418e45803884.png)

Hii , 
I am very new to this platform. I ran the hello world and its working fine. But when I run testGPIO.c it shows error as attached in the picture.

Can somebody help?

**Comment by quangdaovu** [comment]
You should include spi.h to testGPIO.c.

`#include "spi.h"`

**Comment by ravi02011993** [comment]
Hi, I tried that. Now i am getting an error as below.
error: 'FUNC_EXT2' undeclared (first use in this function)
   set_pin_function(PIN_MSPI_CSN1, FUNC_EXT2);

**Comment by quangdaovu** [comment]
Eventhough FUNC_EXT2 doesn't exist but I believe its value is 0. You can just replace it with 0, or add it to sw/libs/sys_lib/inc/gpio.h, under FUNC_GPIO.

**Comment by ravi02011993** [comment]
Thank you 👍
