### ISSUE TITLE
Problem running  cmake_configure.zeroriscy.gcc.sh

### ISSUE THREAD

**Issue by SumanthKK** [pulp-platform/pulpino#176]
Hi,

To evaluate the pulp processor cores for our projects, I am trying to generate the PULPino zeroriscy (as I do not have access to ETH compiler) processor core without any customization by running the "cmake_configure.zeroriscy.gcc.sh" as per the instructions mentioned on your GitHub page. I am getting an error as the compiler broken, below is the error message snippet for your reference. 

![image](https://user-images.githubusercontent.com/31291198/36558683-c96bd330-17d9-11e8-8aaa-304c4c6dffa5.png)

 I have installed the toolchain suite correctly by running the below commands as mentioned in the RISC-V software toolchain page. I am not sure if the error is because of the incorrect tool installation or with zeroriscy configure script. Can you please take a look at the below tool installation commands and let me know if I missed anything or added anything extra. 
	
```

1. export TOP=$(pwd)
2. git clone https://github.com/riscv/riscv-tools.git
3. cd $TOP/riscv-tools
4. git submodule update --init --recursive
5. export RISCV=$TOP/riscv
6. export PATH=$PATH:$RISCV/bin
7. Installed the g++ compiler at it is missing
8. Execute the ./build-spike-only.sh command, this will install the risc-V components.
9. cd $TOP/riscv-tools/
10. ./configure --prefix=$RISCV --with-arch=rv32gc --with-abi=ilp32d
11. make linux
12. make report linux 

```

Let me know if you need any further information. I appreciate your help.

Thanks,
Sumanth.

**Comment by quangdaovu** [comment]
You can get ETH toolchain here:

https://github.com/pulp-platform/ri5cy_gnu_toolchain

Remember to build it with make ZERORISCY=1.

**Comment by SumanthKK** [comment]
I have already installed this toolchain as well. But I am getting the same error. Not sure if we need to anything to the linux PATH, as I see nothing has been mentioned on the page.

**Comment by quangdaovu** [comment]
Make sure that your PATH contains only ETH path.

**Comment by SumanthKK** [comment]
Thanks much for the prompt response! 

Whats the ETH you want me to set? I remember the webpage says that ETH compiler is not needed for zeroriscy core and also the compiler is not released to the public. Can you please elaborate on this?

Thanks!

**Comment by quangdaovu** [comment]
riscv-toolchain, specifically you need riscv32-unknown-elf-gcc compiler and friends. There are two choices for this toolchain: Either using the official RISC-V toolchain supported by Berkeley or the custom RISC-V toolchain from ETH. The ETH versions supports all the ISA extensions that were incorporated into the RI5CY core as well as the reduced base instruction set for zero-riscy. Please make sure you are using the newlib version of the toolchain.

Actually it's needed. And I don't really get your question. What do you mean by set ETH?

**Comment by SumanthKK** [comment]
Sorry for the confusion! I meant by the ETH compiler path. There are a lot of sub-directories inside the ri5cy_gnu_toolchain  directory, which directory path should I add to the Linux path? Is it the one highlighted in the below figure?

![image](https://user-images.githubusercontent.com/31291198/36561065-a6ba3726-17e0-11e8-8966-a8a95feebf15.png)

From your comment, what I understand is that it's better to install only the ri5cy_gnu_toolchain tool suite. Am I correct?

**Comment by quangdaovu** [comment]
Yep you're correct. Remove whatever related to official RISCV toolchain in your PATH, leave only ETH things. 
For ETH toolchain, if you follow the guide on README then you should include ~/R_work/pulpino/ri5cy_gnu_toolchain/install/bin

**Comment by SumanthKK** [comment]
Great! It worked! I am assuming that I can use any of the cores by using your tail chain and setting respective variables, correct me if I am wrong.
And also, I was with the idea that the scripts generate the zeroriscy core as well. Do I need to clone the core separately?

**Comment by quangdaovu** [comment]
I haven't try other cores, mine is ri5cy core and its corresponding toolchain works fine with zeroriscy script, even with compile helloworld (of course my custom "helloworld"). So, if you can then clone the toolchain with different build option is the best, but if you're too lazy to wait (for the build process) then I bet you can give a try.

**Comment by FrancescoConti** [comment]
@SumanthKK if you refer to the `update-ips.py` / `generate-scripts.py`, those are used to download the RTL both for RISCY and zero-riscy. BTW, I see no reason for which the zero-riscy toolchain should not work on RISCY - zero-riscy supports a strict subset of instructions AFAIK.

**Comment by SumanthKK** [comment]
@FrancescoConti , The GitHub PULPino repository page mentions that installation of the other cores except Zero-riscy needs the ETH compiler. So I was wondering if the zero-risky tool chain supports the other cores. Can you please clarify me if the ETH compiler is released to public and part of your tool-chain?
