### ISSUE TITLE
Understanding the flow for hello world

### ISSUE THREAD

**Issue by ravi02011993** [pulp-platform/pulpino#178]
Hi all,

I am new to Pulpino. I installed the software and run the helloworld program and the output is displayed 
in vsim console. Thats fine. 
I did not understand how the hello world is transmitted through UART. I just attached the block diagram.
Could someone help me understanding the how the output is displayed via. UART?

![image](https://user-images.githubusercontent.com/28788219/36589348-45d3b904-188b-11e8-82a8-1439abbd11a2.png)

**Comment by gautschimi** [comment]
the uart has memory mapped registers in the apb address space which the 
core can access with normal read/write instructions. the path in the 
block diagram looks like this:

core -> data interface -> bridge -> axi4 bus -> bridge -> apb bus -> uart
