### ISSUE TITLE
Regarding new hardware accelerator

### ISSUE THREAD

**Issue by ravi02011993** [pulp-platform/pulpino#181]
Hi all,
I have to add a new hardware accelerator to APB bus. So I made a dummy peripheral and added it along with all other peripherals that are connected to APB. when I give the command "make vcompile" it does not compile the new peripheral slave.  I think it is not detecting the peripheral. And when I try to simulate I got the same error.
Please help me how to solve the issue

Regards
Ravindranath

**Comment by FrancescoConti** [comment]
Did you add the dummy peripheral in a new source file? If so, you will need to update https://github.com/pulp-platform/pulpino/blob/master/vsim/vcompile/build_rtl_sim.csh to make this visible from `make vcompile`.

BTW, see issue #142 for some people having similar needs.

**Comment by ravi02011993** [comment]
Ok. Thank you
