### ISSUE TITLE
compile annotate

### ISSUE THREAD

**Issue by LilachDery** [pulp-platform/pulpino#194]
Hello
1. in pulpino/sw/utils - how to compile the annotate.py ? (I want to add another register to the output file - trace_core_00_0.log)
2. I'm looking for the branch_taken flag/register. I saw it in one of your data sheets and I want to put this register in the trace.

Thanks

**Comment by zarubaf** [comment]
You need to modify the tracer not the annotation script. Which btw I highly doubt is working :-)
