### ISSUE TITLE
Does ri5cy core from pulpino support c++ stl. 

### ISSUE THREAD

**Issue by MaddyR** [pulp-platform/pulpino#197]
I have a requirement wherein I need ri5cy core to have c++ stl vectors.  I suppose this won't be supported with pulpino due to the dynamic allocation nature which may come in with c++ and STL.  Just to be sure is it still possible

**Comment by FrancescoConti** [comment]
The core is feature-complete, it supports any kind of programming language provided that you have the related compiler and runtime. The compiler should be fine, but you will have to port a C++ runtime, AFAIK we do not support C++.
