### ISSUE TITLE
Question about riscv-toolchain

### ISSUE THREAD

**Issue by huangchengxtu** [pulp-platform/pulpino#2]
Hi
When i use the official RISC-V toolchain supported by Berkeley,always installing riscv64-unknown-elf-gcc,not riscv32-unknown-elf-gcc .what are the differences between them? 
Or what do i need to do?

thanks,wait for you anser!

**Comment by atraber** [comment]
Hi

riscv64-unknown-elf-gcc is intended for a 64-bit RISC-V target. Our core however is 32-bit only, so you will need the riscv32-unknown-elf-gcc.

When configuring the RISC-V gnu toolchain, just append `--with-xlen=32`. This should then build the 32-bit version of it which is compatible with our core.

Cheers
Andy

**Comment by riteish4141** [comment]
Hello,

Can you please elaborate where to append '--with-xlen=32' ?
