### ISSUE TITLE
Add tcsh in requirements

### ISSUE THREAD

**Issue by pacalet** [pulp-platform/pulpino#20]
tcsh is the shell used for Modelsim compilations and simulations. As many people do not use it, it would probably be helpful to indicate this and to advice users of a different shell to:
- install tcsh
- create a ~/.tcshrc file containing, at least something equivalent to:

> setenv PATH ${PATH}:/somepath/modeltech/bin
> setenv LIBRARY_PATH /usr/lib/x86_64-linux-gnu

**Comment by gautschimi** [comment]
yes modelsim should be available
