### ISSUE TITLE
stages

### ISSUE THREAD

**Issue by LilachDery** [pulp-platform/pulpino#207]
Hello,

I am trying to understand the "riscy core overview" - the architecture of the processor. 

How many stages does the processor have?

thanks

**Comment by barrydebruin** [comment]
Hey,

Some information about the RISCV core can be found in this paper:
- A near-threshold RISC-V core with DSP extensions for scalable IoT Endpoint Devices
url: https://arxiv.org/abs/1608.08376

Especially Figure 2c. will be useful for you. You can see that the RISCY core has a 4-stage pipeline.

**Comment by zarubaf** [comment]
You can also have a look here:
https://pulp-platform.org//wp-content/uploads/2017/11/ri5cy_user_manual.pdf
