### ISSUE TITLE
pulpino document

### ISSUE THREAD

**Issue by yeyh830101** [pulp-platform/pulpino#212]
Hi Sir,
    Where can I download pulpino document instead of generated by LateX ?    
    Thanks a lot.

**Comment by FrancescoConti** [comment]
https://www.pulp-platform.org/documentation/

**Comment by yeyh830101** [comment]
Thanks ！I have got it.

**Comment by stefanct** [comment]
The link has changed to https://www.pulp-platform.org/docs/pulpino_datasheet.pdf in case anybody wonders.
