### ISSUE TITLE
Linux version requirement

### ISSUE THREAD

**Issue by yeyh830101** [pulp-platform/pulpino#213]
Hi Sir，
     Can the pulpino environment and tool chains  run at 32bit ubuntu ?    64 bit linux is not necessary , right ?
      Thanks.

**Comment by FrancescoConti** [comment]
Nobody of us ever tried to run this on a 32 bit machine. Moreover, there is typically no reason to run a 32 bit OS unless the computer has been built more than 10 years ago - in which case I think it will be a pain to run any simulation on it anyways...
