### ISSUE TITLE
Python3.7 results the below issue

### ISSUE THREAD

**Issue by Sesib** [pulp-platform/pulpino#222]
python update-ips.py results the below issues

File "update-ips.py", line 53
    print tcolors.ERROR + "ERROR: could not find remote server." + tcolors.ENDC
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tcolors.ERROR + "ERROR: could not find remote server." + tcolors.ENDC)?

**Comment by FrancescoConti** [comment]
The tools require `python2`.

**Comment by Nagatejapallapu** [comment]
File "./update-ips.py", line 53
    print tcolors.ERROR + "ERROR: could not find remote server." + tcolors.ENDC
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tcolors.ERROR + "ERROR: could not find remote server." + tcolors.ENDC)?
