### ISSUE TITLE
RISC-V Privileged ISA Specification

### ISSUE THREAD

**Issue by cgarlati** [pulp-platform/pulpino#223]
Apologies in advance if this is not the right forum for the question:

Does Pulpino support RISC-V Privileged ISA Specification and U-Mode in particular? 

If not, is there any plan to comply with these RISC-V standard extensions?

see https://riscv.org/specifications/privileged-isa/

Thanks!
Cesare

**Comment by davideschiavone** [comment]
Dear Cesare,
PULPino does not support priviledge ISA specs but we are planning to integrate such features in the riscv core: https://github.com/pulp-platform/riscv

for M and U mode with the PMP.

Best,
Davide
