### ISSUE TITLE
Problem about ModelSim

### ISSUE THREAD

**Issue by hyf6661669** [pulp-platform/pulpino#224]
In the README.MD, you say that the users should use ModelSim to compile the RTL code. But I find that the latest ModelSim 10.5 only supports Windows OS. So I try to install ModelSim 10.2c on my computer with Debian9 (based on Linux Kernel 4.9.x). However, it failed. The Google tells me that the Linux kernel 4.x is not compatiable with ModelSim 10.2c. At last, I have to install CentOS7 (based on Linux Kernel 3.10.x). Luckily, I can compile the RTL code using ModelSim successfully.

But I'm wondering how to finish those operations with Linux Kernel 4.x.x? Since our team is using the latest Linux Kernel, it will take lots of time and effort to change the OS.  

I'm looking forward to your favourable reply, thanks!!!

**Comment by zarubaf** [comment]
We are using CentOS. My work machine is on 3.10.0
