### ISSUE TITLE
error in "make vcompile"

### ISSUE THREAD

**Issue by merchantf** [pulp-platform/pulpino#232]
I am getting this error in "make vcompile"

./vcompile/build_rtl_sim.csh: Command not found.
make[3]: *** [CMakeFiles/vcompile] Error 1
make[2]: *** [CMakeFiles/vcompile.dir/all] Error 2
make[1]: *** [CMakeFiles/vcompile.dir/rule] Error 2
make: *** [vcompile] Error 2

Can you help me with this one?

Thanks & Regards,
Farhad

**Comment by zarubaf** [comment]
There should be a long thread which lists possible problems and solutions. Please refer to it:

#170
