### ISSUE TITLE
Cannot connect to the network at startup

### ISSUE THREAD

**Issue by abdullahyildiz** [pulp-platform/pulpino#25]
I manually start the network as follows:

```
ifconfig eth0 hw ether 02:01:02:03:04:08 #just assigned random 6 octets
ifconfig eth0 192.168.1.80 up
route add default gw 192.168.1.1
```

However, I cannot use ssh service. Restarting sshd manually didn't work.

**Comment by gautschimi** [comment]
hm can you give some more information?
what have you done already? can you connect over uart?
what is not working when you try to ssh?

**Comment by abdullahyildiz** [comment]
I can connect over UART (/dev/ttyPS1) to ZedBoard.

The following messages are displayed while the system is booting:

> Sending DHCP and RARP requests ...... timed out!
> IP-Config: Reopening network devices...
> Sending DHCP and RARP requests ...... timed out!
> IP-Config: Auto-configuration of network failed

I restart sshd manually and then run from my computer

`ssh root@192.168.1.80`

However, nothing happens

**Comment by gautschimi** [comment]
there was indeed an issue in the Ethernet setup. the Ethernet frequency was somehow corrupted, I've just pushed a fix. if you rebuild the whole fpga it should work again. if you want i can also share the boot.bin etc.

best,
michael

**Comment by abdullahyildiz** [comment]
OK. It worked. Thanks for your help.

**Comment by abdullahyildiz** [comment]
By the way, what is the root password? Password 'pulp' did not work while trying to connect over ssh.
