### ISSUE TITLE
How to debug on RTL platform by jtag_dpi? jtag_dpi cannot create the tcp port:4567

### ISSUE THREAD

**Issue by shiner-chen** [pulp-platform/pulpino#259]
According section:Interactive Debug(https://github.com/pulp-platform/pulpino#interactive-debug), the debug bridge depends on the jtag_dpi package that emulates a JTAG port and provides a TCP socket to which the jtag bridge can connect to. I follow the guide(https://github.com/pulp-platform/debug_bridge/blob/master/README.md) , but cannot work. The jtag_dpi should create the TCP port 4567,  but I cannot find it by command "netstat -a|grep 4567" . Why?

**Comment by shmoib** [comment]
@shiner-chen  did you find a solution to this issue? did you find any complete working steps?
