### ISSUE TITLE
stdout of PULPino

### ISSUE THREAD

**Issue by abdullahyildiz** [pulp-platform/pulpino#27]
Which pins of ZedBoard are used for stdout of PULPino? It seems you've used EMIO connections of Zynq device for UART0 but I couldn't find location constraints within project files of pulpemu. Or did I miss something?

**Comment by abdullahyildiz** [comment]
I think there is no such pin going outside from ZedBoard, ttyPS0 which corresponds to UART0 is connected to PULPino on programmable logic.

**Comment by gautschimi** [comment]
stdout goes over uart to the ps (so internal). it will be pasted on the console which means you should see it when you login to the ps with minicom or ssh.

**Comment by abdullahyildiz** [comment]
What is the baudrate of UART0 which is connected over /dev/ttyPS0?

**Comment by z419379295** [comment]
Hi,

I also have this question, what is the baud rate of UART0 which is connected over /dev/ttyPS0? If it is not standard baud rate, how can we observe the output of PULPino using Minicom? It misses some characters.

Best,
Ken
