### ISSUE TITLE
compilation code size is too BIG !

### ISSUE THREAD

**Issue by jeffcjlin** [pulp-platform/pulpino#287]
First, I compile a very simple program and checking the .bin file code size.
This simple program directory location is sw/apps/riscv_tests/basic/basic.c

I paste the compilation flow details below:
-----------------------------------------------------------
/pulpino/sw/test1/apps/riscv_tests/basic# make
-- GCC_MARCH= IMFDXpulpv2
-- USE_ZERO_RISCY= 0
-- RISCY_RV32F= 1
-- ZERO_RV32M= 0
-- ZERO_RV32E= 0
-- PL_NETLIST=
-- Configuring done
-- Generating done
-- Build files have been written to: /srv/jefflin/pulpino/sw/test1
[100%] Built target bench
[100%] Built target crt0
[100%] Built target string
[100%] Built target sys
[100%] Built target math_fns
[100%] Built target Arduino_core
[100%] Built target Arduino_separate
[100%] Built target rv_basic.elf
[100%] Generating vectors/stim.txt
[100%] Built target rv_basic.stim.txt
[100%] Generating modelsim.ini
[100%] Generating work
[100%] Built target rv_basic.links
[100%] Built target rv_basic.slm.cmd
[100%] Built target rv_basic.bin.cmd
[100%] Built target rv_basic.s19.cmd
---------------------------------------------------------------------------
After compilation is finished, I check the code size of rv_basic.bin
The size of rv_basic.bin is 1049836 Bytes.

Why this simple application code size is so BIG ?

I attach the compilation files size details for reference below.
-------------------------------------------------------------------------------------------
root@0d76d73a0a65:/srv/jefflin/pulpino/sw/test1/apps/riscv_tests/basic# ls -la
total 276
drwxr-xr-x  7 root root    4096 Mar 15 10:08 .
drwxr-xr-x 25 root root    4096 Mar 15 10:07 ..
drwxr-xr-x 26 root root    4096 Mar 15 10:08 CMakeFiles
-rw-r--r--  1 root root     668 Mar 15 10:07 CTestTestfile.cmake
drwxr-xr-x  2 root root    4096 Mar 15 04:14 FS
-rw-r--r--  1 root root   22402 Mar 15 10:07 Makefile
-rw-r--r--  1 root root     862 Mar 15 04:14 cmake_install.cmake
lrwxrwxrwx  1 root root      38 Mar 15 10:08 modelsim.ini -> /srv/jefflin/pulpino/vsim/modelsim.ini
-rwxr-xr-x  1 root root 1049836 Mar 15 10:01 rv_basic.bin
-rwxr-xr-x  1 root root   71804 Mar 15 10:01 rv_basic.elf
-rwxr-xr-x  1 root root  114226 Mar 15 10:01 rv_basic.s19
drwxr-xr-x  2 root root    4096 Mar 15 10:01 slm_files
drwxr-xr-x  2 root root    4096 Mar 15 04:14 stdout
lrwxrwxrwx  1 root root      35 Mar 15 10:01 tcl_files -> /srv/jefflin/pulpino/vsim/tcl_files
drwxr-xr-x  2 root root    4096 Mar 15 04:14 vectors
lrwxrwxrwx  1 root root      31 Mar 15 10:01 waves -> /srv/jefflin/pulpino/vsim/waves
lrwxrwxrwx  1 root root      30 Mar 15 10:08 work -> /srv/jefflin/pulpino/vsim/work

**Comment by hyf6661669** [comment]
Hello, can you upload the dumped file generated by riscv32-unknown-elf-objdump?
