### ISSUE TITLE
can we implement pulpino on nexys4?

### ISSUE THREAD

**Issue by zzlzzlwithzzl** [pulp-platform/pulpino#365]
Because our professor is suspected of having covid, so he cannot go to university, the only available board we can use is nexys4, and he asked us to try this board.

**Comment by quangdaovu** [comment]
PULP's cores don't rely on external component. I don't see any reason why it can't be implement on other FPGA board.

**Comment by zzlzzlwithzzl** [comment]
@quangdaovu thank you! but nexys4 doesn't have arm core, if i need to do it, i should generate a new processing system on microblaze, anyway i already got a zybo board.
