### ISSUE TITLE
I'm trying to install the pulpino i am getting the error

### ISSUE THREAD

**Issue by Nagatejapallapu** [pulp-platform/pulpino#377]
Using remote PULPino url https://github.com/pulp-platform/pulpino.git
Cloning into 'pulpino'...
remote: Enumerating objects: 10050, done.
remote: Total 10050 (delta 0), reused 0 (delta 0), pack-reused 10050
Receiving objects: 100% (10050/10050), 17.14 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (6209/6209), done.
Checking connectivity... done.
Using remote git server https://github.com, remote is https://github.com/pulp-platform
Cloning into 'ipstools'...
remote: Enumerating objects: 974, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 974 (delta 14), reused 19 (delta 6), pack-reused 945
Receiving objects: 100% (974/974), 192.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (675/675), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "./update-ips.py", line 86, in <module>
    import ipstools
  File "/root/pulpino/tmp/pulpino/ipstools/__init__.py", line 15, in <module>
    from .IPDatabase import *
  File "/root/pulpino/tmp/pulpino/ipstools/IPDatabase.py", line 16, in <module>
    import yaml
ImportError: No module named yaml
ERROR: could not update IPs

**Comment by Werni2A** [comment]
The Python script has an additional dependency on PyYAML. You can install it via `python2 -m pip install pyyaml`.

I'm also struggling with the installation/simulation of Pulpino so please let me know when you get it running.

**Comment by Nagatejapallapu** [comment]
you can externally download the Yaml package
