### ISSUE TITLE
make helloworld.vsim

### ISSUE THREAD

**Issue by aledolme** [pulp-platform/pulpino#392]
Hello everyone.
I'm trying to compile the simplest test of pulpino, but I'm encountering some troubles.
Version control and the first steps of running simulation are good. When I try yo compile helloworld.vsim examples, I get the following error:

**Entering directory '/home/pulpino/sw/build'
[  0%] Building C object libs/bench_lib/CMakeFiles/bench.dir/src/bench.c.o
/home/pulpino/sw/libs/bench_lib/src/bench.c:1:0: error: bad value (IMXpulpv2) for -march= switch
 // Copyright 2017 ETH Zurich and University of Bologna.
Entering directory '/home/Desktop/pulpino/sw/build'
[  0%] Building C object libs/bench_lib/CMakeFiles/bench.dir/src/bench.c.o
/home/Desktop/pulpino/sw/libs/bench_lib/src/bench.c:1:0: error: bad value (IMXpulpv2) for -march= switch
 // Copyright 2017 ETH Zurich and University of Bologna.**

Which can be the problem?

Thanks you

**Comment by sharad2000** [comment]
Hi 

Did you solve this error?
Can you please explain how.
