### ISSUE TITLE
External i2c slave sensor

### ISSUE THREAD

**Issue by aitor4321** [pulp-platform/pulpino#400]
Hello, I'm trying to add an external slave temperature sensor that operates via I2C signals. I have modified the PULPemu top files by changing the I2C part of the OLED to the following:

module pulpemu_top(....,
 i2c_scl,
 i2c_sda
);
  inout         i2c_sda;
  inout         i2c_scl;

  assign i2c_scl = (~scl_oen) ? scl_out : 1'bz;
  assign scl_in = i2c_scl;
  assign i2c_sda = (~sda_oen) ? sda_out : 1'bz;
  assign sda_in = i2c_sda;

I have also added the following lines to the "impl.tcl" file for the "scl" and "sda" pins:

set_property PACKAGE_PIN V10 [get_ports {i2c_scl}];
set_property PACKAGE_PIN W8 [get_ports {i2c_sda}];

After doing this, I compiled it, and it did not give me any errors.

I used this file to load the program into the RAM: 

#include <stdio.h>
#include "i2c.h"
#include "utils.h"
#include "string_lib.h"
#include "uart.h"

#define TMP112_ADDRESS 0x48 

#define TMP112_REG_TEMP 0x00
#define TMP112_REG_CONFIG 0x01

void configureTMP112() {
    i2c_send_command(I2C_START_WRITE);
    i2c_send_data(TMP112_ADDRESS << 1);
    i2c_send_command(I2C_WRITE);
    i2c_send_data(TMP112_REG_CONFIG);
    i2c_send_command(I2C_WRITE);
    i2c_send_data(0x00); 
    i2c_send_command(I2C_STOP);
}

float readTemperature() {
   
    i2c_send_command(I2C_START_WRITE);
    i2c_send_data(TMP112_ADDRESS << 1);
    i2c_send_command(I2C_WRITE);
    i2c_send_data(TMP112_REG_TEMP);
    i2c_send_command(I2C_STOP);

    i2c_send_command(I2C_START_READ);
    i2c_send_data((TMP112_ADDRESS << 1) | 0x01);
    i2c_send_command(I2C_READ);

    int tempRaw = i2c_get_data() << 4; 
    tempRaw |= (i2c_get_data() >> 4) & 0x0F; 
    i2c_send_command(I2C_STOP);

  
    float temperature = (float)tempRaw * 0.0625;

    return temperature;
}

int main() {
    printf("hola\n");
    i2c_setup(0x63, 0x08);
    configureTMP112(); 
   
    while (1) {
        float temperature = readTemperature();
        printf("Temperatura: %.1f C\n", temperature);
 
    }

}

I uploaded the necessary files to boot PULPino on a Zedboard, and I have launched the program. I have analyzed the signal with a logic analyzer, but it's not receiving any signal. Any help?

**Comment by MateaSamuel** [comment]
Hy @aitor4321 ,
I want to make something similar like you with the difference that I want to use a sensor with UART interface.
Have you any idea how can I route the signal of rx and tx to pmod, editing the pulpemu project?
Any ideas/advice will help me.

Thank you in advance!

**Comment by aitor4321** [comment]
Hi @MateaSamuel,
Yes, you can consider using the SPI slave to load the program and route the RX and TX signals to the PMOD. In that way, you can indeed use the UART for your UART sensor.

**Comment by MateaSamuel** [comment]
Thanks for your answer...I'll try it.
