### ISSUE TITLE
Spiload and GLIBC version issue

### ISSUE THREAD

**Issue by marci89** [pulp-platform/pulpino#47]
Hello,
I'm trying to run a custom program on the pulpino platform. I've accomplished all the steps as the readme file shows (the one within the FPGA folder). I have a running version of Linux (xilinx version) on a zybo development board and I can run commands correctly with both UART and ssh.
When I try to run spiload in order to run my custom program I get this error:

./spiload: /lib/libc.so.6: version `GLIBC_2.17' not found (required by ./spiload)

I compiled spiload, as well as the xilinx linux, with arm-xilinx-linux-gnueabi-gcc 4.9.1.

Anyone that got this error could help me?

Thank you very much

**Comment by marci89** [comment]
![img_20161213_153053](https://cloud.githubusercontent.com/assets/8887468/21177231/83a8f59e-c1ea-11e6-98c3-fb7c26b802cd.jpg)

**Comment by gautschimi** [comment]
Does that only happen when you run your custom application or for all 
applications?

can you check if you have glibc_2.17 on the arm platform?

**Comment by marci89** [comment]
hi gautschimi,

it happens when I run spiload, with whichever application.

when I run /lib/libc.so.6 through the arm terminal, I get the message in the screenshot below

![glibc](https://cloud.githubusercontent.com/assets/8887468/21178714/1b6bec32-c1f1-11e6-8f28-5648731d40af.png)

so the version seems to be GNU C Library version 2.11.1

As I said, I compiled the xilinx linux, as well as spiload, with the xilinx toolchain (arm-xilinx-linux-gnueabi-gcc 4.9.1)

It seems that the glib used within the arm platform has been pre-compiled and the one that I use for compiling spiload is newer. But I've no idea of how I can upgrade the glibc in the arm platform.
