### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by jpavieira** [pulp-platform/pulpino#49]
Will you have future support for python? meaning that I can run my python script on the core.

I need to use TensorFlow libraries to run my script on pulpino, but this libraries are only available on python. 

Thank you

**Comment by gautschimi** [comment]
Currently there is no plan to extend pulpino with python.

**Comment by be4web** [comment]
That being said, the problem with running TensorFlow on PULPino is not the lack of python support. In fact, TF only provides python bindings which makes it convenient for people to write scripts for it. The backend is (optimised) C++ that heavily relies on an unix-like OS. Even projects like tinyDNN make use of syscalls.
