### ISSUE TITLE
Use Vivado instead of Modelsim

### ISSUE THREAD

**Issue by abdallah93as** [pulp-platform/pulpino#51]
Hello guys

I was following your tutorial on how to compile the pulpino, and I got to the part of: "make vcompile"
Now the problem is that modelsim is not working on linux, and i have tried everything i can to make it run.Modelsim works on windows but the cygwin enviroment does not contain some of the prerequisite packages.

So my question is: can i do this with vivado, and if so. can you please tell me how???

**Comment by gautschimi** [comment]
Hello

we are using modelsim in linux and it works. We have no plans to port everything to windows.

we are using vivado to build our fpga target, but you can certainly also use it's simulator for rtl simulations. but we have not looked into this.
