### ISSUE TITLE
Compilation error for PUPL tests

### ISSUE THREAD

**Issue by hoangt** [pulp-platform/pulpino#52]
Hi All,

When I compile testALU for PULPINO by "make all" in sw/build folder, there are errors on instructions as below

```
[ 38%] Building C object apps/riscv_tests/testALU/CMakeFiles/testALU.elf.dir/testALU.c.o
/home/hoangt/WORK/TOOLS/pulp/pulpino/sw/apps/riscv_tests/testALU/testALU.c: Assembler messages:
/home/hoangt/WORK/TOOLS/pulp/pulpino/sw/apps/riscv_tests/testALU/testALU.c:217: Error: unrecognized opcode `p.ror a5,a4,a3'
/home/hoangt/WORK/TOOLS/pulp/pulpino/sw/apps/riscv_tests/testALU/testALU.c:224: Error: unrecognized opcode `p.ror a2,s1,a2'
/home/hoangt/WORK/TOOLS/pulp/pulpino/sw/apps/riscv_tests/testALU/testALU.c:230: Error: unrecognized opcode `p.ror a2,s1,a2'
/home/hoangt/WORK/TOOLS/pulp/pulpino/sw/apps/riscv_tests/testALU/testALU.c:236: Error: unrecognized opcode `p.ror a2,s1,a2'

```

I used riscv-toolchain priv1.7 and believed that does not support instriction "p.ror" ? Could you let me know correct riscv-toolchain (version and commit number) which can compile all PULP tests

Thank you !

**Comment by gautschimi** [comment]
Which toolchain are you using exactly?

You should use the one provided by us. you can find it here:
https://github.com/pulp-platform/ri5cy_gnu_toolchain

**Comment by hoangt** [comment]
Hi Michael,

I have installed the toolchain downloaded from that link and problem was
solved. Thank you for kind reply

/Tung
