### ISSUE TITLE
AXI and APB simulations

### ISSUE THREAD

**Issue by Aregaard** [pulp-platform/pulpino#67]
Are there any simulations test for the AXI and APB? I am trying to write a hardware accelerator for the PULPino and need to see the signals to/from the APB/AXI and how they work.

**Comment by gautschimi** [comment]
I'd have a look at the official specifications of arm where you will 
find axi4 and apb interface specifications

http://infocenter.arm.com/help/index.jsp

(under AMBA -> AMBA 4 -> AMBA APB Protocol specifications or AMBA AXI 
Protocol specifications

**Comment by amohamme** [comment]
Is it possible to connect external module to PULPino via its AXI or APB interface ?
