### ISSUE TITLE
Where is RISCV compiler from ETH?

### ISSUE THREAD

**Issue by GioAgu17** [pulp-platform/pulpino#72]
Hi,

I saw that on the README of the project it is recommended to install the RISCV toolchain from ETH, but I can't find no toolchain except for that of Berkeley University.

Could you please help me?
Thanks,
Giovanni

**Comment by gautschimi** [comment]
https://github.com/pulp-platform/ri5cy_gnu_toolchain

**Comment by GioAgu17** [comment]
great

thanks
Giovanni

2017-05-12 13:43 GMT+02:00 Michael Gautschi <notifications@github.com>:
