### ISSUE TITLE
tcl/ips_inc_dirs.tcl -- No file

### ISSUE THREAD

**Issue by susi655** [pulp-platform/pulpino#74]
In fpga folder, while executing make got error.
"tcl/ips_inc_dirs.tcl" no such file or directory

**Comment by susi655** [comment]
solved

**Comment by ameyapatil619** [comment]
Hi, I still see this issue. How did you go about solving this?

**Comment by FrancescoConti** [comment]
You must generate the file by running `update-ips.py` or `generate-scripts.py` in the pulpino root.

**Comment by ameyapatil619** [comment]
I couldn't run the .py files due to a missing yaml package. Installed the necessary dependencies and works fine.
