### ISSUE TITLE
Ever made a comparison with MicroBlaze by Xilinx?

### ISSUE THREAD

**Issue by GioAgu17** [pulp-platform/pulpino#85]
Hi,

just for the sake of curiosity. Have you ever made to do a comparison between PULPino and MicroBlaze on ZedBoard in terms of execution time and power consumption?

Thank you in advance for the attention,
Giovanni

**Comment by gautschimi** [comment]
we have not done such a comparison in our group. but we would be 
interested in the results!

best,

Michael
