### ISSUE TITLE
CSR exc_cause_n write issue

### ISSUE THREAD

**Issue by timdudu** [pulp-platform/pulpino#88]
The write logic of exc_cause_n is:
  12'h342: if (csr_we_int) exc_cause_n = {csr_wdata_int[5], csr_wdata_int[4:0]};

The exc_cause[5:0] is read as {rdata[31],rdata[4:0]}. So I think the write logic should be:
  12'h342: if (csr_we_int) exc_cause_n = {csr_wdata_int[31], csr_wdata_int[4:0]};

**Comment by davideschiavone** [comment]
Hi timdudu, 

Indeed you are right.

We are going to change  the write logic.

Thanks,
Davide
