### ISSUE TITLE
After "wfi" instruction execution, the core could not be waken up by only enable interrupt

### ISSUE THREAD

**Issue by susanbear230** [pulp-platform/pulpino#91]
Hi guys,

Recently we were doing some instruction tests on pulpino and we found that the behavior of "wfi" instruction is not aligned with the description in ISA specification: after "wfi" instruction the core enters sleep mode, only enable interrupt(the IER in event unit) could not wake up the core from "wfi". So I am so appreciated if you could make me clearer on my understanding of "wfi".
I am referring to the <Draft Privileged ISA Specification v1.10> at https://riscv.org/specifications/privileged-isa/, in page 38, the description of Wait for Interrupt part:
_If an enabled interrupt is present or later becomes present while the hart is stalled, the interrupt
exception will be taken on the following instruction, i.e., execution resumes in the trap handler and
mepc = pc + 4._
From the ISA specification we know that the expected behavior for interrupt is to wake up the core from "wfi" and resume execution with mepc = pc + 4 after interrupt is serviced.
But in our real test(enable a timer interrupt, then execute "wfi"), we get the below result:
Configuration|Behavior
--|--
Event enable & Interrupt disable | Core could be woken up and exit wfi to continue program processing, only event pending bit is on.
Event disable & Interrupt enable | Core could be woken up to execute interrupt, then back to sleep.
Event disable & Interrupt enable & Event pending bit on | Core could be woken up and exit wfi to continue program processing after interrupt is serviced
In conclusion, **only event could wake up core from "wfi" while interrupt could not**. For the second configuration, event disable and interrupt enable, due to the core did not resume execution, we guess that the mepc is not increased to pc+4 but keeping the pc, so every time interrupt returns, the core continues to get "wfi" instruction to enter sleep again.  However, after print out the mepc value in IRQ handler, we found that the mepc already changed to pc+4 but after interrupt is serviced and returns with "eret", the core enters sleep again and stops execution.
I fully understand the flexibility of having both events and interrupts, but the question is why only event could wake up the core while interrupt could not?  Regarding to "wfi" instruction specification, such implementation seems does not meet the behavior.

Best Regards,
Susan

**Comment by davideschiavone** [comment]
Dear Susan,

you are right, in pulpino the wfi is not compliant but we aligned the WFI behavior in the master branch used in out new microcontroller PULPissimo that you can find here: https://github.com/pulp-platform/pulpissimo

Basically the microprocessor is the same expect the interrupt and wfi handling and the relative sleep mode. Which is now compliant and handled by the core itsefl rather than the event unit.

Best regards,
Davide




Best Regards,
Susan
