### ISSUE TITLE
Zedboard new password request

### ISSUE THREAD

**Issue by federicoVS** [pulp-platform/pulpino#95]
I type the following command `ssh root@x.x.x.x` and I they ask me the password. After I inserted the correct one I get the following:

```
WARNING: Your password has expired.
You must change your password now and login again!
```
I insert a new password but I get the same message. How can I fix this?

**Comment by gautschimi** [comment]
you can set a more up to date time before defining a password

date -s year-month-day hours:minutes:seconds
