### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by ChristianPalmiero** [pulp-platform/pulpino#99]
Hi everyone,
I was wondering if it would be possible to build and run an application by providing command line parameters.
Thank you.

**Comment by be4web** [comment]
I am not really sure what you are actually meaning. If you have a look at the [crt0.S](https://github.com/pulp-platform/pulpino/blob/master/sw/ref/crt0.riscv.S) you can see that main gets called there. If you want to pass some parameters you can put them in `a0` or `a1`.

**Comment by ChristianPalmiero** [comment]
Thanks a lot!
